# log4j uses 6 levels, namely TRACE, DEBUG, INFO, WARN, ERROR and FATAL
status = info
name = SchemaDemo

property.basePath = logs

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d %p %C{1.}[%t] - %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = STDOUT
