<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mx="https://mmixm.aero/features/4" xmlns:mb="https://mmixm.aero/base/4" targetNamespace="https://mmixm.aero/base/4" elementFormDefault="qualified" version="4.0.0">
	<xs:annotation>
		<xs:documentation>This package contains elements describing a person or an organization.</xs:documentation>
	</xs:annotation>
	<xs:import namespace="https://mmixm.aero/features/4" schemaLocation="../features/qualification.xsd"/>
	<xs:include schemaLocation="datatype.xsd"/>
	<xs:include schemaLocation="contactInfo.xsd"/>
	<xs:complexType name="AtowOrganization">
		<xs:annotation>
			<xs:documentation>Complex type containing descriptors about the ATOW Organization.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="atowCode" type="mb:ATOWCodeType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The 3-5 character code that reflects the routing code of a Technical Operations element. Each routing symbol includes a three-letter alphabetical prefix that identifies the FAA organization involved, per FAA Order 1100.87G.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="atowCodeChangeProvenance" type="mb:Provenance" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The date/time when routing code was last changed.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="districtOfficeName" type="mb:String150Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of District Office in the organization's hierarchy, as described in Order 1100.87 Routing Symbol Standards.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="groupName" type="mb:String150Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of Group in the organization's hierarchy, as described in Order 1100.87 Routing Symbol Standards.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="locId" type="mb:FsepLocIdType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Location ID of an ATOW organization.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="previousAtowCode" type="mb:ATOWCodeType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The last routing code associated with the asset, prior to the current code.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="serviceAreaName" type="mb:String150Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of Service Area in the organization's hierarchy, as described in Order 1100.87 Routing Symbol Standards.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sscName" type="mb:String150Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Name of System Support Center in the organization's hierarchy, as described in Order 1100.87 Routing Symbol Standards.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CageCode">
		<xs:annotation>
			<xs:documentation>The Commercial and Government Entity Code, or CAGE Code, is a unique identifier assigned to suppliers to various government or defense agencies, as well as to government agencies themselves and also various organizations.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="cageCode" type="mb:String5Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The Commercial and Government Entity Code, or CAGE Code, is a unique identifier assigned to suppliers to various government or defense agencies, as well as to government agencies themselves and also various organizations.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CostCenter">
		<xs:annotation>
			<xs:documentation>Complex type containing the cost center code.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="costCenterCode" type="mb:CostCenterType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>This five-character code field contains the organization assigned maintenance responsibility.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Organization">
		<xs:annotation>
			<xs:documentation>Complex type containing organization name and additional information.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="additionalInformation" type="mb:AdditionalInformation" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Additional information about an organization.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="atowOrganization" type="mb:AtowOrganization" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Organizational information specific to the FAA's Air Traffic Organization Technical Operations service unit.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="organizationContact" type="mb:Person" minOccurs="0" maxOccurs="99">
				<xs:annotation>
					<xs:documentation>Person associated with the organization.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="organizationName" type="mb:String150Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The name of the organization</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Person">
		<xs:annotation>
			<xs:documentation>Grouping of elements identifying a Person.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="additionalInformation" type="mb:AdditionalInformation" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Additional information about a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ndcEmpId" type="mb:NdcEmpIdType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>National Data center (NDC) employee ID of a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="organization" type="mb:Organization" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Organization associated with the person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="personContact" type="mb:ContactInformation" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Person contact information.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="personName" type="mb:PersonName" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The full name of a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="personQualification" type="mx:Qualification" minOccurs="0" maxOccurs="99">
				<xs:annotation>
					<xs:documentation>Qualification (certification or credential) associated with a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PersonName">
		<xs:annotation>
			<xs:documentation>First name of the person</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="firstName" type="mb:String50Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The first name of a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="lastName" type="mb:String50Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The last name of a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="middleName" type="mb:String50Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The middle name of a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="suffix" type="mb:String10Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Suffix associated with a person's name.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="title" type="mb:String50Type" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Title associated with a person.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
